# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

#install! 'cocoapods',
  #generate_multiple_pod_projects: true,
  #share_schemes_for_development_pods: true

target 'IOWalletProximityExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOWalletProximityExample
  #pod 'IOWalletProximity', :path => '../'
  spm_pkg "IOWalletProximity", :relative_path => "../../../iso18013-ios/"

  target 'IOWalletProximityExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOWalletProximityExampleUITests' do
    # Pods for testing
  end

end
