name: Build, Release and Deploy IOWalletProximity

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.0.0"
  push:
    tags:
      - "*.*.*" # Trigger for every tag x.y.z

jobs:
  build-release:
    runs-on: macos-15-xlarge
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Extract tag version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            # Extract tag removing "refs/tags/"
            echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          fi

      - name: Update podspec version
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          echo "Updating podspec version to ${VERSION}"
          sed -i '' "s/s.version\s*=\s*\".*\"/s.version      = \"${VERSION}\"/" IOWalletProximity.podspec

      - name: Build XCFramework
        run: |
          chmod +x ./.build.sh
          ./.build.sh

      - name: Zip XCFramework
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          cp LICENSE .archives/
          cd .archives
          zip -r "IOWalletProximity-${VERSION}.xcframework.zip" IOWalletProximity.xcframework LICENSE

      - name: Create GitHub Release and Upload Asset
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"                  
          gh release create $VERSION --latest --generate-notes          
          gh release upload $VERSION ".archives/IOWalletProximity-${VERSION}.xcframework.zip" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup-ruby
        uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 #v1.238.0
        with:
          bundler-cache: true

      # This will deploy the SDK to CocoaPods and generate the xcframework
      - name: Deploy on CocoaPods
        env:
          # 1. Run this to register a session: `pod trunk register ioapptech@pagopa.it 'PagoPA S.p.A.'`
          # 2. Confirm the email link.
          # 3. Run this to get the token: `pod trunk me --verbose`
          # 4. Extract the Authentication token from the output and save it in the GitHub secrets as COCOAPODS_TRUNK_TOKEN
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          bundle exec pod trunk push IOWalletProximity.podspec --allow-warnings --verbose
          echo "CocoaPods deployment completed for version ${VERSION}"
