name: Swift Unit Tests

on:
  workflow_dispatch:

  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  RESULT_BUNDLE: TestResults.xcresult

# Limit permissions to only what is necessary for the workflow
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: set-xcode-version
        run: sudo xcode-select -s '/Applications/Xcode_16.2.app/Contents/Developer'
        shell: bash

      - uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.235.0
        with:
          bundler-cache: true

      - name: Install Dependencies
        run: |
          cd IOWalletProximityExample
          gem install bundle
          bundle install
          bundle exec pod install --repo-update

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project IOWalletProximity/IOWalletProximity.xcodeproj \
            -scheme IOWalletProximity \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0.1' \
            -resultBundlePath ${{ env.RESULT_BUNDLE }}

      - name: Convert XCResult → JUnit XML
        run: |
          brew tap a7ex/homebrew-formulae
          brew install xcresultparser
          xcresultparser -o junit ${{ env.RESULT_BUNDLE }} > junit-results.xml

      - name: Publish JUnit summary
        uses: dorny/test-reporter@6e6a65b7a0bd2c9197df7d0ae36ac5cee784230c # v2.0.0
        with:
          name: Swift Unit Tests Summary
          path: junit-results.xml
          reporter: java-junit

      - name: Report Test Status
        if: always()
        run: |
          if [ ${{ job.status }} == "failure" ]; then
            echo "::error::Unit tests failed. Please check the logs for details."
            exit 1
          fi
